#
# LIB = library name
# SRC = list of source files the library is made of.
# LOCAL_CFLAGS = list of private Compiler flags
# WARNING : if library is a local one, comment the line after install:
# ( Do not install in project lib dir )
#

LIB = libstrutil.a
LIBD = libstrutil.d.a
SRC = main.c
LOCAL_CFLAGS =

.SUFFIXES: .uil .uid .do

include	${PROJECT_HOME}/Commons/makefiles/makefile.libstd
# DO NOT DELETE THIS LINE -- make depend depends on it.
