#
# Template makefile
# EXE = name of final executable
# SRC = list of source files
# LOCAL_CFLAGS = list of private Compiler flags
# LOCAL_LIBES = list of libraries to use ( in -lxxx format )
# DIP_LIBS = list of library pathnames used by the application
#

EXE =
SRC =
LOCAL_CFLAGS = -O
LOCAL_LIBES = -lxxx
DIP_LIBS = /usr/prj/lib/libxxx.a

include	/usr/prj/makefiles/makefile.std
