#
# Template makefile
# EXE = name of final executable
# SRC = list of source files
# LOCAL_CFLAGS = list of private Compiler flags
# LOCAL_LIBES = list of libraries to use ( in -lxxx format )
# DIP_LIBS = list of library pathnames used by the application
#

CC = gcc
AR = ar
LIB = libshm.a
LIBD = libshm.d.a
SRC = main.c
LOCAL_CFLAGS = -g -I ../include

include	${PROJECT_HOME}/Commons/makefiles/makefile.libstd
# DO NOT DELETE THIS LINE -- make depend depends on it.
